name: CI/CD
on: push
  braches:
    - 'main'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - run: npm ci
      - run: npm run build
  
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - run: npm ci
      - run: npm run lint

    deploy:
      needs: build
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout
        - uses: sebastianpopp/ftp-action
          with:
            host: ftp.gavinmccabe.com
            user: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: ./build
            remoteDir: testDeploy

