name: CI/CD
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint

  deploy:
    needs: [build, lint]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp.gavinmccabe.com
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build
          remoteDir: testDeploy
